import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import 'leaflet/dist/leaflet.css';


const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`relative ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* ✅ Toast: bottom-right and tighter icon spacing */}
        <Toaster
          position="bottom-right"
          reverseOrder={false}
          toastOptions={{
            style: {
              minWidth: '340px',
              maxWidth: '480px',
              padding: '10px 14px', // tighter overall padding
              fontSize: '1rem',
              borderRadius: '10px',
              background: '#1f2937',
              color: '#fff',
              boxShadow: '0 6px 20px rgba(0, 0, 0, 0.3)',
              display: 'flex',
              alignItems: 'center',
              gap: '8px', // ✅ reduces the space between the icon and text
            },
            success: {
              iconTheme: {
                primary: '#22c55e',
                secondary: '#1f2937',
              },
            },
            error: {
              iconTheme: {
                primary: '#ef4444',
                secondary: '#1f2937',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
