name: Build App

on:
  push:        # Runs on push to any branch
  pull_request: # Runs on PR to any branch

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21

      - name: Install Dependencies
        run: bun install

      - name: Build App
        run: bun run build
